### PR TITLE
* fixed #4

### LINKED ISSUE #4: fails to read larger database
Hi.

I don't quite know how to reproduce this yet, but I have a database that fails to read. There were some small entries added first, but then a large entry was added, and updated a few times. 

trace:
```
# node backup-glacier.js 
oops : TypeError: Cannot call method 'push' of undefined TypeError: Cannot call method 'push' of undefined
    at free (/root/cronscripts/node_modules/flat-file-db/index.js:92:21)
    at /root/cronscripts/node_modules/flat-file-db/index.js:107:10
    at Array.forEach (native)
    at populateFreelist (/root/cronscripts/node_modules/flat-file-db/index.js:105:10)
    at parseDatabase (/root/cronscripts/node_modules/flat-file-db/index.js:80:2)
    at Database.openSync (/root/cronscripts/node_modules/flat-file-db/index.js:220:2)
    at Function.open.sync (/root/cronscripts/node_modules/flat-file-db/index.js:246:5)
    at /root/cronscripts/backup-glacier.js:37:23
```

file: http://manticore.2y.net/temp/backup.jdb.gz (1.8M)

### PR DESCRIPTION
**Pull request by veselov**
same problem as in my previous PR, but took a lot longer to find :)

### CODE REVIEW

**Comment by veselov** [comment]
Ping?

**Comment by mafintosh** [comment]
sorry forgot about this. could you fix the indentation? other than that this LGTM

**Comment by veselov** [comment]
That better?

**Comment by mafintosh** [comment]
awesome thanks

**Comment by mafintosh** [comment]
released in 0.1.5. i've added you as collaborator as well incase you find other fixes :)

**Comment by veselov** [comment]
Thank you! :)

**Pull request merged**
